#-------------------------------
# General Site Settings

menu:
- {name: '3D', url: ''}
- {name: 'Drawing',     url: 'drawing'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Autumn Embers',   url: 'proj-1'}
- {name: 'Killzone Light',   url: 'proj-2'}
- {name: 'Piween', url: 'proj-3'}
- {name: 'Ducky', url: 'proj-4'}
- {name: 'Capsule 341',  url: 'proj-5'}
- {name: 'Generated Love',  url: 'proj-6'}


#-------------------------------
# Contact Section

social:
- {icon: 'envelope',  link: 'mailto:mailto:cassandra.hantzen@hotmail.fr'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/cassandra-h-957762152/'}
- {icon: 'instagram', link: 'https://www.instagram.com/cassandra_hantzen/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio with my projects in 3D and Drawing/Comic '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
